#!/usr/bin/env ruby
# coding: utf-8

url         'http://retter.example.com/'
title       '<%= name %>'
description '<%= name %>'
author      '<%= ENV["USER"] %>'
renderer    Retter::Markdown::PygmentsRenderer

# Callbacks for retter sub-command: edit, rebind, commit
#
#   Syntax:
#     after [command], [invoke command or proc]
#
#   Using symbol example:
#     after :rebind, :commit
#
#   Using proc example:
#     after :commit do
#       if yes?("Deploy now? [yes/no]")
#         system "cd #{config.retter_home}"
#         system 'git push origin master'
#       end
#     end
#
#     after :edit do
#       Retter::Site.reset!
#       ident = ARGV.pop
#
#       preview ident if yes?("Preview now? [yes/no]")
#     end
#
# Skip binding:
#  examples:
#    allow_binding :none
#    allow_binding [:profile, :entries, :feed]
#
#  Anyway index page will be bound.
