#!/usr/bin/env ruby
# coding: utf-8

url         'http://retter.example.com/'
title       '<%= name %>'
description '<%= name %>'
author      '<%= ENV["USER"] %>'
renderer    Retter::Renderers::PygmentsRenderer

## Callbacks for retter sub-command: edit, rebind, commit
##
## Syntax:
##   after [command], [invoke command or proc]
#
## Using symbol example:
#    after :rebind, :commit
#
## Using proc example:
#    after :commit do
#      if yes?("Deploy now? [yes/no]")
#        system "cd #{config.retter_home}"
#        system 'git push origin master'
#      end
#    end
#
#    after :edit do
#      ident = ARGV.pop || 'today'
#      preview ident if yes?("Preview now? [yes/no]")
#    end
